/**:
  ros__parameters:
    general:
      camera_model: 'zedx'
      camera_name: 'virtual' # overwritten by launch file
      grab_resolution: 'SVGA' # The native camera grab resolution. '4K', 'HD1200', 'HD1080', 'SVGA', 'AUTO'
      grab_frame_rate: 30 # ZED SDK internal grabbing rate (HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)

    pos_tracking:
      pos_tracking_enabled: true
      pos_tracking_mode: 'GEN_1'
      publish_tf: false
      publish_map_tf: false
      area_memory: false
            
    sensors:
      sensors_image_sync: true
      publish_imu: false
      publish_imu_raw: false
      publish_temp: false
      publish_mag: false
      publish_baro: false
    gnss_fusion:
      gnss_fusion_enabled: false