# not the standard ROS node config parameters, these are topics passed to the image enhancement launch file
front_cam:
  cam_topic: /zed/zed_node/rgb/color/rect/image
  enhanced_topic: /vision/front_cam/image_enhanced

down_cam:
  cam_topic: /vision/down_cam/image_raw
  enhanced_topic: /vision/down_cam/image_enhanced

general:
  sim: false