# not the standard ROS node config parameters, these are topics passed to the vision pipeline launch file
camera:
  front_camera_topic: /zed/zed_node/rgb/color/rect/image
  down_camera_topic: /down_cam/image_raw

image_enhancenment:
  front_enhanced_topic: /vision/front_cam/image_enhanced
  down_enhanced_topic: /vision/down_cam/image_enhanced

object_detection:
  front_object_detection_topic: /vision/front_cam/object_detections
  down_object_detection_topic: /vision/down_cam/object_detections
  front_object_detection_relative_path: /models/frontcam.pt
  down_object_detection_relative_path: /models/downcam.pt

general:
  sim: false
  debug: false