name: Docker Images Main CI

on:
  push:
    branches: [ "main", "pooltest/*", "dev/*" ]
  pull_request:
    branches: [ "main", "pooltest/*" ]
    
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Docker Tag (e.g., 2026-01 or dev)'
        required: true
        default: 'dev'

  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build-x86:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive    # if you vendor msgs/firmware/etc
          lfs: true

    - name: Login to DockerHub
      if: github.event_name == 'workflow_dispatch'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/dev
        file: Docker/dev/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name == 'workflow_dispatch' }}
        tags: mcgillrobotics/auv_2026:${{ inputs.tag_name || 'dev' }}-amd64

  build-arm:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write

    steps:
    - name: Git checkout with LFS and submodules
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive
          lfs: true

    - name: Login to DockerHub
      if: github.event_name == 'workflow_dispatch'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/dev
        file: Docker/dev/Dockerfile
        platforms: linux/arm64
        push: ${{ github.event_name == 'workflow_dispatch' }}
        tags: mcgillrobotics/auv_2026:${{ inputs.tag_name || 'dev' }}-arm64

  build-jetson:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write

    steps:
    - name: Git checkout with LFS and submodules
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive
          lfs: true

    - name: Log in to Docker Hub
      if: github.event_name == 'workflow_dispatch'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/jetson
        file: Docker/jetson/Dockerfile
        platforms: linux/arm64
        push: ${{ github.event_name == 'workflow_dispatch' }}
        tags: mcgillrobotics/auv_2026:${{ inputs.tag_name || 'dev' }}-jetson