name: Docker Images Main CI

on:
  push:
    branches: [ "main", "pooltest/*", "dev/*" ]
  pull_request:
    branches: [ "main", "pooltest/*" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build-x86:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive    # if you vendor msgs/firmware/etc
          lfs: true

    - name: Set up Docker Buildx for cache usage
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/dev
        file: Docker/dev/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: mcgillrobotics/auv_2026:dev-amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write

    steps:
    - name: Git checkout with LFS and submodules
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive    # if you vendor msgs/firmware/etc
          lfs: true

    - name: Set up Docker Buildx for cache usage
	- uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/dev
        file: Docker/dev/Dockerfile
        platforms: linux/arm64
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: mcgillrobotics/auv_2026:dev-arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-jetson:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write

    steps:
    - name: Git checkout with LFS and submodules
      uses: actions/checkout@v4
      with:
          fetch-tags: true
          submodules: recursive    # if you vendor msgs/firmware/etc
          lfs: true

    - name: Set up Docker buildx
    - uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and optionally push image
      uses: docker/build-push-action@v6
      with:
        context: Docker/jetson
        file: Docker/jetson/Dockerfile
        platforms: linux/arm64
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: mcgillrobotics/auv_2026:jetson
        cache-from: type=gha
        cache-to: type=gha,mode=max
